#!/bin/bash
# Setup conda environment for the relayTTS daemon (Qwen3-TTS on Apple Silicon).
#
# Runtime deps are installed from requirements.txt when it exists — a
# hash-pinned lockfile generated by pip-compile from requirements.in.
# `pip install --require-hashes` fails closed if any artifact's SHA-256
# doesn't match the lock, which defends against a tampered package or a
# compromised index. Do NOT `pip install --upgrade` ad hoc; to change a
# dependency:
#
#   1. edit requirements.in
#   2. pip-compile --generate-hashes --allow-unsafe --output-file requirements.txt requirements.in
#   3. re-run the concurrency smoke test
#   4. commit requirements.in + requirements.txt (the pre-commit hook runs pip-audit)
#
# If requirements.txt does not yet exist (fresh clone before first lock), deps
# are installed loose from requirements.in directly.
set -euo pipefail

ENV_NAME="relaytts"
CONDA_BASE="$(conda info --base)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# NOTE: espeak-ng / misaki / phonemizer are intentionally NOT installed here.
# Qwen3-TTS has no G2P phonemizer step — it speaks directly from text.
# The only runtime system binary is ffmpeg (brew install ffmpeg), used by the
# daemon for pitch-preserving time-stretch; install that separately if needed.

# Create the env if it doesn't exist yet
if ! conda info --envs 2>/dev/null | grep -q "^${ENV_NAME} "; then
    echo "Creating conda environment '${ENV_NAME}'..."
    conda create -n "$ENV_NAME" python=3.11 -y -c conda-forge
fi

source "${CONDA_BASE}/bin/activate" "$ENV_NAME"

if [ -f "$SCRIPT_DIR/requirements.txt" ]; then
    echo "Installing pinned, hash-verified runtime dependencies..."
    pip install --require-hashes -r "$SCRIPT_DIR/requirements.txt"
else
    echo "requirements.txt not found — installing loose deps from requirements.in..."
    echo "(Generate a pinned lockfile later with: pip-compile --generate-hashes --allow-unsafe --output-file requirements.txt requirements.in)"
    pip install -r "$SCRIPT_DIR/requirements.in"
fi

# Dev tooling for maintaining the lockfile (not part of the runtime surface, so
# intentionally not in the hash-pinned lock).
pip install pip-tools pip-audit

echo ""
echo "Environment '${ENV_NAME}' is ready."
echo "Activate with: conda activate ${ENV_NAME}"
