#!/bin/bash
# Setup conda environment for the relayTTS daemon.
#
# Runtime deps are installed from requirements.txt when it exists — a
# hash-pinned lockfile generated by pip-compile from requirements.in.
# `pip install --require-hashes` fails closed if any artifact's SHA-256
# doesn't match the lock, which defends against a tampered package or a
# compromised index. Do NOT `pip install --upgrade` ad hoc; to change a
# dependency:
#
#   1. edit requirements.in
#   2. pip-compile --generate-hashes --allow-unsafe --output-file requirements.txt requirements.in
#   3. commit requirements.in + requirements.txt (the pre-commit hook runs pip-audit)
#
# If requirements.txt does not yet exist (fresh clone before first lock), deps
# are installed loose from requirements.in directly.
#
# The daemon owns no model — soundfile, numpy and pyyaml, and nothing else.
# MLX and mlx-audio are deliberately absent: there is no local-inference mode
# for a box to fall back to. HTTP is urllib from the standard library, so
# there is no client dependency either.
set -euo pipefail

ENV_NAME="relaytts"
CONDA_BASE="$(conda info --base)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for arg in "$@"; do
    case "$arg" in
        -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
        *) echo "unknown option: $arg (try --help)" >&2; exit 2 ;;
    esac
done

REQ_IN="requirements.in"
REQ_TXT="requirements.txt"
echo "Setting up '${ENV_NAME}'."

# NOTE: espeak-ng / misaki / phonemizer are intentionally NOT installed here.
# Qwen3-TTS has no G2P phonemizer step — it speaks directly from text.
# The only runtime system binary is ffmpeg (brew install ffmpeg), used by the
# daemon for pitch-preserving time-stretch; install that separately if needed.

# Create the env if it doesn't exist yet
if ! conda info --envs 2>/dev/null | grep -q "^${ENV_NAME} "; then
    echo "Creating conda environment '${ENV_NAME}'..."
    # --override-channels is load-bearing: without it conda still consults the
    # implicit "defaults" channels, and a modern miniconda refuses to proceed
    # until Anaconda's commercial Terms of Service are accepted —
    #   CondaToSNonInteractiveError: Terms of Service have not been accepted
    # which fails env creation outright on any fresh machine. conda-forge is
    # what this line already asked for; this makes that actual.
    conda create -n "$ENV_NAME" python=3.11 -y --override-channels -c conda-forge
fi

source "${CONDA_BASE}/bin/activate" "$ENV_NAME"

if [ -f "$SCRIPT_DIR/$REQ_TXT" ]; then
    echo "Installing pinned, hash-verified runtime dependencies from $REQ_TXT..."
    pip install --require-hashes -r "$SCRIPT_DIR/$REQ_TXT"
else
    echo "$REQ_TXT not found — installing loose deps from $REQ_IN..."
    echo "(Generate a pinned lockfile later with: pip-compile --generate-hashes --allow-unsafe --output-file $REQ_TXT $REQ_IN)"
    pip install -r "$SCRIPT_DIR/$REQ_IN"
fi

# Dev tooling for maintaining the lockfile (not part of the runtime surface, so
# intentionally not in the hash-pinned lock).
pip install pip-tools pip-audit

echo ""
echo "Environment '${ENV_NAME}' is ready."
echo "Activate with: conda activate ${ENV_NAME}"
echo ""
echo "The daemon needs a remote endpoint to run. Register the service with one:"
echo "  RELAYTTS_REMOTE_URL=https://<host>:<port>/v1 RELAYTTS_REMOTE_MODEL=<id> ./build.sh"
